### ISSUE TITLE
README.MD in the API Folder doesnt have the code u copy pasted into the config.json in the #1 Part of this series Please Respond

### ISSUE THREAD

**Issue by iFlyn-karam-def** [D-Clone/Website#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by theADAMJR** [comment]
It uses .env now, and it can be found here - https://github.com/D-Clone/api#env.
