### ISSUE TITLE
Bug when creating an account

### ISSUE THREAD

**Issue by zMarceloUS** [D-Clone/Website#11]
When Creating an Account I put a Username and a Password and I click on accept terms and then I click on confirm and it is on the same screen I click on login I put the password and username but it gives an error

Device: Android
Browser: Chrome

**Comment by zMarceloUS** [comment]
Now I read the: Max users have been reached for Alpha testing and sign-up may be available in the near future.
If you cannot sign-up then this is why.

**Comment by theADAMJR** [comment]
Sign-up limit will be removed with the upcoming v2 release (at https://accord.app), later today.
