### ISSUE TITLE
Emoji selector not centered

### ISSUE THREAD

**Issue by TheOreoTM** [D-Clone/Website#12]
The emoji selector is slightly off the screen. And the chat box is also not centered on the bottom it is slightly at the bottom. I dont know if this is a intended feature or not, just wanted to inform you

![image](https://user-images.githubusercontent.com/82890192/117575148-fd6c2380-b0f9-11eb-9993-4b326e41b91b.png)

**Comment by theADAMJR** [comment]
:thinking:

**Comment by theADAMJR** [comment]
Hidden emoji picker for now.
