### ISSUE TITLE
Role Creation broken

### ISSUE THREAD

**Issue by samosaman73** [D-Clone/Website#13]
Upon creating a role, the role list will just glitch. 

GIF Screenshot: https://samosaman.likes.cash/kokbgblmh9a

**Comment by theADAMJR** [comment]
This bug seems to be re-creatiable on the website, but not in local development.

**Comment by theADAMJR** [comment]
Planned to be fixed soon.

**Comment by theADAMJR** [comment]
Possible cause:
```
...
<a *ngFor="let role of guild.roles.reverse()">
...
```
This caused the roles to reverse order every time each ngFor item is checked.
