### ISSUE TITLE
Error before login and after logged in

### ISSUE THREAD

**Issue by colderryboy** [D-Clone/Website#15]
# Bug Report

Once I logged out and tried to login in back, it prevents me and gives the Unauthorized error. Then I registered a new account and logged in with that, but now if I click on guild or DM it gives the unauthorized error.

**Images:**
While logging:- https://i.imgur.com/FSMcnvc.png
After logged in by registering a new account:- https://i.imgur.com/HKhP1is.png

Browser:  Chrome Version 93.0.4577.82 (Official Build) (64-bit)

**Comment by theADAMJR** [comment]
The API removed the email and other private data to stop it being seen by others.
The properties were set to undefined, then saved, which unintentially bricked accounts.

**Comment by theADAMJR** [comment]
If you logged in with the accord v2 update (this or last week), this info applies to you:

Your email has been reset to: `<username>-<discriminator>@example.com`.
Example: `Adam24-0001@example.com`.
If the username had spaces in they have been replaced by underscores: `Adam_24-0001@example.com`.

It's recommended for you to reset this in your user settings after logging in. The bug has now been fixed and emails don't delete themselves anymore. This affects 22 out of 105 saved user accounts, including mine.

Again, accord.app is currently in a primitive state although more testing should be done to help prevent things like this in the future.
