### ISSUE TITLE
Tag changing from 0001 to 0002

### ISSUE THREAD

**Issue by colderryboy** [D-Clone/Website#16]
# Bug Report

If you have the tag 0001 and you change your email, it gets change to 0002. I don't know if it's a hint of changing tag in the future but yeah, reporting it as bug.

Steps to reproduce:

- Login to your account
- Must have the 0001 tag
- Go to settings
- Change your email (even if the email address is random)
- Save it.

**Comment by theADAMJR** [comment]
Changing username, then changing back to old username should now revert it back.
