### ISSUE TITLE
Invite people not working?

### ISSUE THREAD

**Issue by colderryboy** [D-Clone/Website#19]
####   The guild invite people option not working and can't really seem to generate an invite code.

**Comment by theADAMJR** [comment]
Seems to be a problem on the production build, and not the development build. For some reason the production build can introduce new bugs when building with webpack.

**Comment by theADAMJR** [comment]
This was due to a building React apps uglyfying function names so they don't work with Redux.
`function CreateInvite() {}` become `function e() {}` which was ambiguous.
