### ISSUE TITLE
Ability to exit a Guild via a channel.

### ISSUE THREAD

**Issue by DavidCavallaro** [D-Clone/Website#22]
**Describe the bug**
You can see "Leave Guild" through channels instead of server settings.

**To Reproduce**
1. Go to the left side of a server screen.
2. Press any channel with the right button
3. "Leave Guild" will be visible

**Expected behavior**
Instead of "Leave Guild" there should be a channel change or something else available. The "Leave Guild" entry should only be available by left clicking on the server name.

**Screenshots**
<img width="1792" alt="Schermata 2021-10-04 alle 15 17 02" src="https://user-images.githubusercontent.com/68825684/135858963-70d72b83-cf31-41be-bff5-1d7df6767b82.png">

**Desktop (please complete the following information):**
 - OS: 10.15.7 (19H1323)
 - Browser: Google Chrome
 - Version: 94.0.4606.61 (Official Build) (x86_64)

**Comment by theADAMJR** [comment]
Cannot reproduce. It's probably fixed.
