### ISSUE TITLE
Missing Permissions - MANAGE_ROLES

### ISSUE THREAD

**Issue by DavidCavallaro** [D-Clone/Website#23]
**Describe the bug**
It is not possible to create or modify roles despite having the "MANAGE_ROLES" permission.

**To Reproduce**
1. Grant the "MANAGE_ROLES" permission to a certain role
2. Give that role to a user
3. Go to that user on the server roles page
4. Press "Create" or modify a permission of any role below the one it owns.

**Expected behavior**
With this permission it should be possible to edit or add roles to the guild.

**Screenshots**
<img width="1792" alt="Schermata 2021-10-04 alle 15 32 00" src="https://user-images.githubusercontent.com/68825684/135861096-46e52d46-2559-4148-b0fd-b9a0976069b9.png">

**Desktop (please complete the following information):**
- OS: 10.15.7 (19H1323)
- Browser: Google Chrome
- Version: 94.0.4606.61 (Official Build) (x86_64)

**Comment by theADAMJR** [comment]
Thank you David. Also, another feature to add: roles that are higher than the user's highest role should be disabled (it currently should just give an error on the server). I'll look into this soon.

**Comment by DavidCavallaro** [comment]
That was implied! good job! I will continue the hunt :)

**Comment by theADAMJR** [comment]
Deployed a new update to test and fix role management. It ensures that role managers can edit their own role or lower roles, unless they are the owner - then they can edit anything.
![image](https://user-images.githubusercontent.com/28284250/136085131-77ccb8df-442a-46a5-ae17-bc789e1a5be2.png)

Let me know if you still see this bug.

**Comment by DavidCavallaro** [comment]
Here! The function you described works correctly but wouldn't it be better and safer to block the modification of your role and only keep the possibility to make changes to the underlying roles?

**Comment by theADAMJR** [comment]
I was thinking of that but for some reason I forgot how Discord worked and thought that's how they did it.
I guess I was thinking: Do what Discord did first, and logic second.
![image](https://user-images.githubusercontent.com/28284250/136104710-7954652f-0a8d-4dfa-abdb-8e62555ead14.png)

Added a similar feature for member management with backend validation.
![image](https://user-images.githubusercontent.com/28284250/136107192-0389a14a-66ab-4c1a-8fcd-586e9f175e81.png)
