### ISSUE TITLE
Profile picture not uploaded.

### ISSUE THREAD

**Issue by DavidCavallaro** [D-Clone/Website#24]
**Describe the bug**
When I go to change my avatar from the settings via a url, as indicated, this is not loaded and is replaced by a question mark.

**To Reproduce**
1. Copy the link of an image in .png format
2. Go to your account settings and go to "Avatar URL"
3. Replace "/avatars/avatar_grey.png" at the link
4. Save your changes
5. Visit your profile and you will see the question mark.

**Expected behavior**
Perhaps it does not load the image as it is not present on the machine where Accord is hosted but if this is why this phenomenon occurs it is better to remove it as it is useless. If, on the other hand, the intent is precisely to be able to put a profile image with a simple link then it must be solved as the image I have chosen is not replaced by the default avatar.

**Screenshots**
https://user-images.githubusercontent.com/68825684/135869229-c5443f05-14e2-4755-bf29-01feedb63a99.mp4

**Desktop (please complete the following information):**
- OS: 10.15.7 (19H1323)
- Browser: Google Chrome
- Version: 94.0.4606.61 (Official Build) (x86_64)

**Comment by ghost** [comment]
Yeah the image uploaded is not working

**Comment by DavidCavallaro** [comment]
I don't understand if the word "URL" refers to an internet link or to an address of the machine on which it is hosted since it reads "/avatars/avatar_grey.png" and not "https: ///avatars/avatar_grey.png" . let's see what the developers say ^^

**Comment by theADAMJR** [comment]
URL is misleading, but avatarURL is planned to be for local URLs as it's planned to be replaced with an image upload instead of a text input.

**Comment by theADAMJR** [comment]
So only these default avatars are available at this time:

![image](https://user-images.githubusercontent.com/28284250/135914518-ca7eb6be-dfae-4c53-b2f4-1d96146fe584.png)

**Comment by theADAMJR** [comment]
You can now upload your own images for guild icons, user avatars, or message attachments.

**Comment by DavidCavallaro** [comment]
ty ^^
