### ISSUE TITLE
Cannot Send Messages

### ISSUE THREAD

**Issue by Yossi-Batash** [D-Clone/Website#26]
I don't know if It's a bug,
But in accord's official server, I can't send messages in any channel.

How to see the bug:
1. Join to the server with the code `6tD3f7e`
2. Try to send a message in any channel, It probably will decline you.

What supposed to be:
Sends the message in the channel.

Screenshot:
![image](https://user-images.githubusercontent.com/75735370/136016461-72362c3e-288b-4bce-8f50-70bdc253a0b8.png).

System Information:
Windows 10 64bit
OperaGX
2

**Comment by theADAMJR** [comment]
This bug seemed to appear out of nowhere. Proper testing seemed to fix it.
