### ISSUE TITLE
Verifying your account shows "invalid code"

### ISSUE THREAD

**Issue by DavidCavallaro** [D-Clone/Website#27]
**Describe the bug**
Trying to confirm your account via the verification link that is sent to your email, you are redirected to accord.app but there appears to be a problem.

**To Reproduce**
1. Register at accord.app
2. Open your inbox
3. Open the email sent to you to verify your account
4. Click on "Complete Verification"
5. A red entry will appear at the bottom left

**Expected behavior**
The result should be something that is not an error like "invalid code" but something that represents the success of the action like "Account successfully verified" or "Account created successfully".

**Screenshots**
https://user-images.githubusercontent.com/68825684/136103418-d6ed270a-baec-4e12-96f0-bd9dca0440ed.mp4

**Desktop (please complete the following information):**
- OS: 10.15.7 (19H1323)
- Browser: Google Chrome
- Version: 94.0.4606.61 (Official Build) (x86_64)

**Comment by theADAMJR** [comment]
I could not reproduce this. Codes reset when the API restarts, which is a known bug as it's unexpected behaviour for codes to expire prematurely. 

Workaround: Save the email to something random, then change it back to send a new code.

**Comment by DavidCavallaro** [comment]
I tried entering the login credentials I had previously entered, to see if the account confirmation worked, and I succeeded since it made me log in. Does this mean that the code worked even though it told me it was invalid? However, now if I go to my account settings it comes out written "Your email is unverified which means email 2FA is unavailable". It's normal?

**Comment by theADAMJR** [comment]
If your account was verified, you would have to enter the 2FA code sent to your email each login, and it would explicitly say. So you'd have to use the workaround, for now, if you want to verify your account.

**Comment by DavidCavallaro** [comment]
How should i do?

**Comment by theADAMJR** [comment]
> Workaround: Save the email to something random, then change it back to send a new code.
