### ISSUE TITLE
Visual Hint

### ISSUE THREAD

**Issue by DavidCavallaro** [D-Clone/Website#28]
**Is your feature request related to a problem? Please describe.**
When I press the setting wheel, the Accord name and tag are selected and this is very annoying to my eyes. 😡

**Describe the solution you'd like**
When I go to settings my mouse should only touch that and it shouldn't select my information as well.

**Describe alternatives you've considered**
Divide the "selection" perhaps by inserting a name and tag in a box and then the wheel next to it so when I press the wheel my information will not be selected.

**Comment by theADAMJR** [comment]
Implemented.
