### ISSUE TITLE
[BUG] i'm in an guild but not at the same time

### ISSUE THREAD

**Issue by asdu5asg6da8sjd** [D-Clone/Website#31]
**Describe the bug**
i'm in an guild can't leave and open when i try to leave  i get [Member doesn't exist]

**To Reproduce**
1. Click leave guild (if needed the guild id is: 177129442404020224)

**Expected behavior**
Get error "Member doesn't exist"

**Screenshots**
https://ibb.co/hDC0yD8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version:  Latest version of accord

**Additional context**
None

**Comment by theADAMJR** [comment]
I could not reproduce this in a normal guild. Maybe you can access the guild but your user does not appear on the member list. If it's an issue when trying to leave accord.app support and you joined it after September and before October 9th, then it would make more sense as some members were deleted whilst still being saved in the guild in their user document during a database rollback.
