### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bugi778** [D-Clone/Website#32]
Hey, i want to show some suggestions

Starts by here:
> Invite system url *example*: accord.app/invite/random link
> Mobile support?
> Banners?
> Bug fixes on the mobile preview

Please add the first suggestion

26 Oct. 2021 11:26

**Comment by bugi778** [comment]
cake

**Comment by theADAMJR** [comment]
Interesting. I haven't thought of server banners, but the prerequisite is image uploads. Other suggestions are noted too.
