### ISSUE TITLE
[BUG] Infinitely Redirecting 

### ISSUE THREAD

**Issue by ghost** [D-Clone/Website#33]
**Describe the bug**
A portion of the index.html has a script that redirects you infinitely.
```js
(function(l) {
  if (l.search[1] === '/' ) {
      var decoded = l.search.slice(1).split('&').map(function(s) { 
        return s.replace(/~and~/g, '&')
      }).join('?');
      window.history.replaceState(null, null, l.pathname.slice(0, -1) + decoded + l.hash
    );
  }
}(window.location))
```
 
**To Reproduce**
1. Go to 'https://accord.app'

**Expected behavior**
A portion of the index.html has a script that redirects you infinitely.

**Preview**
![image](https://legacy.celeste.photos/uploads/2ed1df83-acad-42d8-95ef-446c8e0a9ec0/UfLg8kaO.gif)

**Additional context**
Remove it to fix it.

**Comment by theADAMJR** [comment]
Thank you. Sometimes an index.html is missing when building with create-react-app. I did get the same problem 1 or 2 days ago for a few minutes, but rebuilding it fixed it. I'm not sure what exactly causes it yet but something in GitHub actions needs to make sure index.html exists.

**Comment by theADAMJR** [comment]
Also, the script that causes the infinite redirects is a workaround script for using React routing with GitHub pages. Sometimes it takes a while for the website cache to update, but it's fixed for now.

**Comment by theADAMJR** [comment]
Added checking for index.html before deploying to GH pages for prevention.
![image](https://user-images.githubusercontent.com/28284250/140657286-6a7a2190-4059-4134-bdec-5cfe6aa8088d.png)
