### ISSUE TITLE
[FEATURE] Customize and Share Themes

### ISSUE THREAD

**Issue by theADAMJR** [D-Clone/Website#38]
**Is your feature request related to a problem? Please describe.**
Themes are cool. Dark theme isn't always the answer. Not everyone wants just a dark theme.

**Describe the solution you'd like**
Add sharable and customizable themes. They will just be a vanilla CSS layer provided by the user that extends the frontend CSS.

_Create Themes_:
- A maximum of 50 themes can be created by a single user (may be adjusted later).

1) Go to User Settings -> Themes -> Create.
2) Input: 'CSS', 'Theme Name'
3) Click 'Create'
4) Share the link
- You should see a link, in a dialog, of the created theme.

_Consume Themes_:
- Only one theme can be applied at a time.

1) Go to a link to active a theme (https://accord.app/themes/:id)
- Like accepting a Discord invite.
- Options:
  - 'Cancel' - exit dialog
  - 'Add' - add theme, but don't change active theme
  - 'Activate' - add theme, and change active theme
2) Go to User Settings -> Themes.
3) Select a different theme
- You can delete themes easily, and reactivate them with the link.

**Describe alternatives you've considered**
Built-in themes - but they are harder to maintain, and seem to cause issues if I write bad CSS.
Not adding themes - but themes are cool.
Chrome extensions - you can achieve the same thing with coding your own theme the hard way, but hardly anyone would want to do that.

**Additional context**
This was the last feature that was added to Accord v1, before I updated the project to React, which removed a lot of the features.

**Comment by itsarakio** [comment]
The girl theme for the app can be interesting. Boys 'tastes are always different from girls'.
For example, I can only be comfortable with a dark theme
But I saw a lot of girls who do not like the dark theme and use the light theme. For the first step, the light theme can be interesting

**Comment by theADAMJR** [comment]
I agree. I don't dislike light theme, and prefer dark theme. In some situations I prefer different themes, especially because the old theme can get boring over time. This is what I didn't like about Windows 10 - just being able to change theme colour. However, it seems that Windows 11 is adding more theme customizability, similar to this feature, while Discord is not adding more themes AFAIK, which creates the demand for apps like BetterDiscord - the same themes can get boring over time.

**Comment by theADAMJR** [comment]
Working on this feature now.
