### ISSUE TITLE
Duplicate mutual server icons

### ISSUE THREAD

**Issue by TheOreoTM** [D-Clone/Website#4]
**Description**
When you click on user profile you can see duplicates of the same guild.

**To Reproduce**
1. Go to any guild
2. Right click on a user
3. Look for mutual server tab
4. There you will see duplicates of the same guild

**Expected behavior**
Should see only one mutual guild icon

**Comment by theADAMJR** [comment]
Guilds may have the same abbreviation and therefore the same icon, which may be confusing.
