### ISSUE TITLE
[BUG] Can't upload image

### ISSUE THREAD

**Issue by ghost** [D-Clone/Website#40]
**Describe the bug**
Unable to upload SVG

**To Reproduce**
1. Upload SVG
2. See error

**Expected behavior**
SVG to upload

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 96

**Comment by theADAMJR** [comment]
SVG's are not supported in the current version, although I see no problem in adding support in future versions for .webp and ,svg files.
