### ISSUE TITLE
[BUG] Module not found after installation

### ISSUE THREAD

**Issue by Jeotique** [D-Clone/Website#41]
**Describe the bug**
Compile error 
`./src/services/format-service.ts
Module not found: Can't resolve '@accord/types/patterns' in 'C:\Users\Jeotique-PC\Desktop\app-2-stable\frontend\src\services'`
**To Reproduce**
I just do everything like in the readme and npm start in frontend

**Screenshots**
![image](https://user-images.githubusercontent.com/71186872/147880873-d21c70a8-6062-4bf4-8dd1-a5dd62f81200.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version idk

**Comment by Jeotique** [comment]
![image](https://user-images.githubusercontent.com/71186872/147881044-467907ec-c517-489e-9379-fd6b9cd4c861.png)

**Comment by theamircodex** [comment]
Hello, have u tried `npm install @accord/types/patterns` ?
