### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Its-SheldonDev** [D-Clone/Website#42]
When i start the server i have error : 

Error: Cannot find module '@accord/types'

but i have installed accord/types module

**Comment by hsyoon2261** [comment]
> When i start the server i have error :
> 
> Error: Cannot find module '@accord/types'
> 
> but i have installed accord/types module

how to install accord/types?

**Comment by theADAMJR** [comment]
The `@accord/types` setup is complex, but there was no viable workaround to this - putting a plain `types` folder in the root folder is ideal, but instead it's in `frontend/src/types`.

So to install `@accord/types` you would do something like `npm i ../frontend/src/types` and not `npm i ../types`.

**Comment by SniffRx** [comment]
> The `@accord/types` setup is complex, but there was no viable workaround to this - putting a plain `types` folder in the root folder is ideal, but instead it's in `frontend/src/types`.
> 
> So to install `@accord/types` you would do something like `npm i ../frontend/src/types` and not `npm i ../types`.

When trying to set accord / types, an error occurs.
```
messenger.sniffrx.ru@SniffServer:~/www/messenger.sniffrx.ru/ds/frontend$ npm i ../frontend/src/types
npm ERR! Can't install /var/www/messenger.sniffrx.ru/data/www/messenger.sniffrx.ru/ds/frontend/src/types: Missing package version

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/messenger.sniffrx.ru/data/.npm/_logs/2022-03-09T07_12_12_045Z-debug.log
```

**Comment by valkyrienyanko** [comment]
> Error: Cannot find module '@accord/types'

I am also getting this error. I am Windows 10 user.

**Comment by theADAMJR** [comment]
I believe I have fixed this error, as it was due to bad symbolic links and incompatibilites between Linux and Windows.
