### ISSUE TITLE
Accord Status

### ISSUE THREAD

**Issue by theADAMJR** [D-Clone/Website#48]
Development has been paused since Feburary. Accord.app is not my main focus currently, but I don't want to 'abandon' accord.
The old domain name (accord.app) was not renewed as it expensive to renew, and is no longer associated with the project.

This may also mean the app could be renamed in the future, who knows... 🤔

The app is also not currently being hosted, as I always seem to have consistent fatal memory leaks when I host using a paid VPS.
I'd like to add that this happened with 3PG as well, a Discord project, in early 2020, although I tried with both projects to find a solution to no avail, although it was only observed to occur on the live VPS environment.

**Comment by cruncher12** [comment]
Yeah - I noticed tht domin expired :( Seems pretty expensive for somone to buy. I really hope developent can start again - my espodts team used to use it. (before the domain expiration, or course)

**Comment by asdu5asg6da8sjd** [comment]
@cruncher12 Accord is now back at [acrd.app](https://acrd.app)!
