### ISSUE TITLE
[BUG] "mkdir -p backend/keys" - "The syntax of the command is incorrect."

### ISSUE THREAD

**Issue by HyperOC12** [D-Clone/Website#49]
get this message when I try to do the following command.

`C:\Users\bluem\OneDrive\Desktop\HCord>mkdir backend/keys`
`The syntax of the command is incorrect.`

I am using Windows 11.

**Comment by theADAMJR** [comment]
Use [Git bash](https://git-scm.com/downloads) for this commands. The CMD command syntax is different.
