### ISSUE TITLE
Mutual severs isnt actually mutual servers

### ISSUE THREAD

**Issue by TheOreoTM** [D-Clone/Website#5]
**Description**
Even though i have my own guild which no one is in when i go and click on adamjr's profile it shows my guild on the mutual servers list.

![image](https://user-images.githubusercontent.com/82890192/116926485-d635d200-ac73-11eb-9c89-bc5d40684a4d.png)

![image](https://user-images.githubusercontent.com/82890192/116926506-d9c95900-ac73-11eb-97fd-28eed8fb2200.png)

**Comment by theADAMJR** [comment]
Thank you.

**Comment by theADAMJR** [comment]
Fixed
