### ISSUE TITLE
Question: Why is the api down most of the time?

### ISSUE THREAD

**Issue by asdu5asg6da8sjd** [D-Clone/Website#51]
The api is down most of the time meaning the app at [Accrd](accrd.app) does not work. Why is that?

**Comment by theADAMJR** [comment]
There were DNS problems with hosting. It's online now.
Hopefully it stays online this time.

**Comment by blindful** [comment]
well. There's a little different issue now.

`acrd.app redirected you too many times.`

**Comment by asdu5asg6da8sjd** [comment]
@theADAMJR well. There's a little different issue now.

`acrd.app redirected you too many times.`

**Comment by asdu5asg6da8sjd** [comment]
(I have tried it in a private window. Still didnt work.)

**Comment by asdu5asg6da8sjd** [comment]
also directly accessing `api.acrd.app` refuses to connect.

**Comment by theADAMJR** [comment]
That was DNS propagation delay, I was also setting up dynamic DNS.
I have setup some metrics to monitor the app [https://accord.statuspage.io](https://accord.statuspage.io).
Any downtime will be shown as a gap in the metrics.
Will reopen until the uptime is more stable.

**Comment by theADAMJR** [comment]
Posting images sometimes seems to crash the API without any error logs.

**Comment by asdu5asg6da8sjd** [comment]
mhm

**Comment by theADAMJR** [comment]
If you upload files that are too large, it crashes the server.
```
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: LIMIT_FILE_SIZE
0|api.acrd.app  |     at new NodeError (node:internal/errors:387:5)
0|api.acrd.app  |     at ServerResponse.writeHead (node:_http_server:314:11)
0|api.acrd.app  |     at ServerResponse.writeHead (/home/ubuntu/accord/backend/node_modules/on-headers/index.js:44:26)
0|api.acrd.app  |     at ServerResponse._implicitHeader (node:_http_server:305:8)
0|api.acrd.app  |     at write_ (node:_http_outgoing:867:9)
0|api.acrd.app  |     at ServerResponse.end (node:_http_outgoing:977:5)
0|api.acrd.app  |     at writeend (/home/ubuntu/accord/backend/node_modules/express-session/index.js:262:22)
0|api.acrd.app  |     at Immediate.onsave (/home/ubuntu/accord/backend/node_modules/express-session/index.js:340:11)
0|api.acrd.app  |     at processImmediate (node:internal/timers:466:21) {
0|api.acrd.app  |   code: 'ERR_HTTP_INVALID_STATUS_CODE'
0|api.acrd.app  | }
```
How large has yet to be determined.

**Comment by blindful** [comment]
mhm. What about 2TB of *insert word that starts with p*?

**Comment by theADAMJR** [comment]
https://github.com/theADAMJR/acrd.app/blob/dev/backend/src/rest/functions/apply-middleware.ts#L42
1MB file limit seems interesting.

**Comment by asdu5asg6da8sjd** [comment]
Let's talk in a guild...

**Comment by asdu5asg6da8sjd** [comment]
I THINK I FOUND ANOTHER BUG... (I'm in only one guild btw)
![image](https://github.com/theADAMJR/acrd.app/assets/72381315/e31f6b05-c0a8-47e0-bca0-bcee6d71f57a)

**Comment by asdu5asg6da8sjd** [comment]
Created a few channels using the Redux Devtools Dispatcher.

![image](https://github.com/theADAMJR/acrd.app/assets/72381315/350ebc98-b2cd-4a71-a1a4-b47b23b20c84)

**Comment by asdu5asg6da8sjd** [comment]
btw scrolling isnt possible. (within the channels list)

**Comment by theADAMJR** [comment]
I will fix the file bug later. There are a decent amount of bugs in accord.

**Comment by asdu5asg6da8sjd** [comment]
I can see. Okay bye now

**Comment by asdu5asg6da8sjd** [comment]
Also. I can say one thing.

The loading message: May work on a Tesla
My response to it: A tesla can run a web browser. Which can run Accord. which can work.

**Comment by theADAMJR** [comment]
API will be offline for today.
I am unable to do anything about now.
Updating MongoDB completely scuffed the database (not the data itself though).
I've also been awake for 22 hours, which makes it a lot easier to solve the problem. 💀

The long term vision will be to keep the server online at least 99.5% of the time.
I say long term because keeping accord in particular online is a massive pain to do.
It will take trial and error, but we will get there eventually.

https://accord.statuspage.io

**Comment by theADAMJR** [comment]
API is online again and the database has been upgraded and wiped.

**Comment by theADAMJR** [comment]
Image uploads are temporarily disabled for now.

**Comment by theADAMJR** [comment]
Image uploads enabled, MongoDB should be stable now.

**Comment by asdu5asg6da8sjd** [comment]
okay.
