### ISSUE TITLE
Friend request remains on pending

### ISSUE THREAD

**Issue by Colderry** [D-Clone/Website#6]
When your friend sends you friend request and you accept it. It stills remains on the pending.

Here is a screenshot:- https://cdn.discordapp.com/attachments/839360007548043284/839360038597296138/pending_bug.PNG

**Comment by theADAMJR** [comment]
Thank you. I'll look into this later.

**Comment by theADAMJR** [comment]
On further investigation, this happens for the receiver after they accept the request.

**Comment by theADAMJR** [comment]
If a user is removed then readded again, a new DM channel is created. It should use the old DM channel instead.

**Comment by Colderry** [comment]
> If a user is removed then readded again, a new DM channel is created. It should use the old DM channel instead.

Yeah! I hope you gonna fix it soon.

**Comment by theADAMJR** [comment]
Tested a fix that stops users adding friends they have already requested or added.
This may be deployed in a few hours.
Please close this issue when you feel comfortable that it's fixed.

**Comment by theADAMJR** [comment]
**Update**: should be deployed tomorrow.
