### ISSUE TITLE
Giving anyone roles on any guild without permissions

### ISSUE THREAD

**Issue by quaccer** [D-Clone/Website#7]
**Describe the bug**
Anyone can give himself any roles on any guild. For example, on the accord.app support guild I gave myself mod.

**To Reproduce**
1. Go to a guild
2. Click on any user
3. You can give him roles

**Expected behavior**
You can't give roles out without permsissions

**Screenshots**
https://ibb.co/0qshs82
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version: 75.0.3969.259
 
**Additional context**
Anyone can give himself the mod/admin role, and has perms to kick/ban

**Comment by theADAMJR** [comment]
Role management has been tweaked for next update.
I believe this was a visual bug with the website as the API checks permissions of the manager before giving roles.
