### ISSUE TITLE
Can't Login Back To An Account

### ISSUE THREAD

**Issue by McpeplayGamesMC** [D-Clone/Website#8]
**Describe the bug**

**To Reproduce**
1. Go to 'Login Section'
2. Click on 'Login'
3. Scroll up to see 'wait to the future to be able to make an new account'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by theADAMJR** [comment]
Removing the message for the login page.
