### ISSUE TITLE
Not letting to add separations sometimes.

### ISSUE THREAD

**Issue by jorgemairlot** [D-Clone/Website#9]
**Describe the bug**
When you write something like: "I am Jorge" the "I am" won't separate and look like this "Iam"

**To Reproduce**
1. Send a message with separations

**Expected behavior**
It does separations correctly

**Screenshots**
https://gyazo.com/a9e9135ce2cb6310b877598fb5271fa0

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Accord application]
 - Version []

**Comment by theADAMJR** [comment]
Fixed in next update.
